# Generated by Django 5.1.6 on 2025-03-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=64)),
                ('hotel_location', models.CharField(max_length=60)),
                ('hotel_rating', models.IntegerField()),
            ],
        ),
    ]
