# Generated by Django 5.1.6 on 2025-03-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_alter_hotel_hotel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
